// Точка входа: подключается последней. Загружает состояние, вешает глобальные обработчики и запускает отрисовку.
state = loadState();
document.addEventListener("click", e => {
  const b = e.target.closest("[data-suggest]"); if (!b) return;
  const input = b.closest("label").querySelector("input"), name = b.dataset.suggest, parts = input.value.split(/[,;]/).map(x => x.trim());
  const last = parts.pop() || ""; if (last && !name.toLowerCase().includes(last.toLowerCase())) parts.push(last);
  parts.push(name); input.value = parts.filter(Boolean).join(", "); input.focus(); input.dispatchEvent(new Event("input"));
});
document.addEventListener("input", e => {
  if (e.target.name !== "scorers") return;
  const q = lastToken(e.target).toLowerCase(), box = e.target.parentElement.querySelector(".suggest"); if (!box) return;
  box.querySelectorAll("button").forEach(b => { b.hidden = !!q && !b.dataset.suggest.toLowerCase().includes(q); });
});
document.querySelector("#season-select").innerHTML=SEASONS.map(s=>"<option "+(s===currentSeason?"selected":"")+">"+s+"</option>").join("");document.querySelector("#season-select").addEventListener("change",e=>{persist();currentSeason=e.target.value;render();});document.querySelector("#history-button").addEventListener("click",()=>{history();document.querySelector("#history-dialog").showModal();});document.querySelectorAll(".close-dialog").forEach(b=>b.addEventListener("click",()=>b.closest("dialog").close()));const arenaPhoto=document.querySelector(".arena-photo");new ResizeObserver(([e])=>arenaPhoto.style.setProperty("--s",e.contentRect.width/1536)).observe(arenaPhoto);document.fonts.ready.then(fitBoardLabels);document.querySelector("#next-match").addEventListener("click",e=>{const i=e.currentTarget.dataset.next;if(i!=="")openMatch(Number(i));else selectSector("competitions");});document.querySelector(".brand").addEventListener("click",e=>{e.preventDefault();document.querySelector(".hero").scrollIntoView({behavior:"smooth"});});on("#calendar-button","click",openCalendar);document.querySelector("#backup-now").addEventListener("click",()=>{exportData();});document.querySelector("#backup-later").addEventListener("click",()=>{lsSet(K_SNOOZE,String(Date.now()+864e5));renderBackupBanner();});document.querySelector("#data-button").addEventListener("click",()=>{const st=document.querySelector("#data-status");st.className="data-status";st.textContent=backupInfo();document.querySelector("#data-dialog").showModal();});document.querySelector("#export-button").addEventListener("click",()=>{const st=document.querySelector("#data-status");st.className="data-status ok";st.textContent="Копия скачана: "+exportData()+". "+backupInfo();});document.querySelector("#import-file").addEventListener("change",async e=>{const f=e.target.files[0],st=document.querySelector("#data-status");e.target.value="";if(!f)return;try{const r=await importData(f);st.className="data-status "+(r?"ok":"");st.textContent=r?"Данные загружены: "+r+".":"Импорт отменён, данные не изменены.";}catch(err){st.className="data-status err";st.textContent="Не удалось загрузить: "+err.message;}});
applyClubIdentity();initAccess();render();initMobileNav();registerPwa();
